apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  labels:
    app: payment-service
data:
  SERVER_PORT: "8084"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://auth-service:9000"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/microservices"
  SPRING_DATASOURCE_USERNAME: "user"
